### ISSUE TITLE
Checks if current logged in user is in session's participants, if not, add them

### ISSUE THREAD

**Issue by Syakhisk** [Syakhisk/partyplaylist-deprecated#22]

**Comment by Xyedo** [comment]
need more info. we always add session participants with array union, either the user has the same name or not
```ts
export const addParticipant = async(id: string, name:string): Promise<void> => {
  await updateDoc(doc(db, COLLECTION_NAME, id), {
    participants: arrayUnion({name}) 
  })
}
```
do you mean like to not update the participants if we already have it in the db? or the add the host to the participants
like this? [image](https://user-images.githubusercontent.com/77372206/228879490-e91358de-fcf0-4de9-9ef9-004f9725f3a8.png)
